///////////////////////////////////////////////////////////////////////////////
// cppCodeServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_cppCode = 0x3F000000;
#define SRVNAME_CPPCODE "cppCode"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_cppCodeCRtContextModule = {0x0116fe3c,0x346f,0x44ef,{0x90,0x69,0x89,0xd2,0xfb,0x46,0x90,0x40}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_RtContextModuleInputs 1
#define ADI_RtContextModuleOutputs 2
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_RtContextModuleState = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_658D4B07_CCBE_463E_B186_5BAD3BAD5B1D_INCLUDED_)
#define _TC_IID_658D4B07_CCBE_463E_B186_5BAD3BAD5B1D_INCLUDED_
TCOM_DECL_INTERFACE("658d4b07-ccbe-463e-b186-5bad3bad5b1d", I_StateMachine)
#endif // !defined(_TC_IID_658D4B07_CCBE_463E_B186_5BAD3BAD5B1D_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _RtContextModuleInputs
{
	SHORT In1;
} RtContextModuleInputs, *PRtContextModuleInputs;

typedef struct _RtContextModuleOutputs
{
	SHORT out1;
} RtContextModuleOutputs, *PRtContextModuleOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
