///////////////////////////////////////////////////////////////////////////////
// cppCodeInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "cppCodeServices.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_658D4B07_CCBE_463E_B186_5BAD3BAD5B1D_INCLUDED_)
#define _TC_TYPE_658D4B07_CCBE_463E_B186_5BAD3BAD5B1D_INCLUDED_
struct __declspec(novtable) I_StateMachine : public ITcUnknown
{
	virtual HRESULT TCOMAPI M_Start()=0;
	virtual HRESULT TCOMAPI M_Stop()=0;
	virtual HRESULT TCOMAPI M_GetState(SHORT& State)=0;
};
_TCOM_SMARTPTR_TYPEDEF(I_StateMachine, IID_I_StateMachine);
#endif // !defined(_TC_TYPE_658D4B07_CCBE_463E_B186_5BAD3BAD5B1D_INCLUDED_)

///</AutoGeneratedContent>
