///////////////////////////////////////////////////////////////////////////////
// cppCodeClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "cppCodeClassFactory.h"
#include "cppCodeServices.h"
#include "cppCodeVersion.h"
#include "RtContextModule.h"

BEGIN_CLASS_MAP(CcppCodeClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB_RT(VID_cppCode, CID_cppCodeCRtContextModule, SRVNAME_CPPCODE "!CRtContextModule", CRtContextModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CcppCodeClassFactory::CcppCodeClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_CPPCODE));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(cppCode));
#endif //defined(TCDBG_UNIT_VERSION)
}

