///////////////////////////////////////////////////////////////////////////////
// RtContextModule.h
#pragma once

#include "cppCodeInterfaces.h"

class CRtContextModule 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public I_StateMachine
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CRtContextModule();
	virtual	~CRtContextModule();

///<AutoGeneratedContent id="InterfaceMembers">
	// I_StateMachine
	virtual HRESULT TCOMAPI M_Start();
	virtual HRESULT TCOMAPI M_Stop();
	virtual HRESULT TCOMAPI M_GetState(SHORT& State);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE_RT();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	SHORT m_State;
	RtContextModuleInputs m_Inputs;
	RtContextModuleOutputs m_Outputs;
///</AutoGeneratedContent>

};
